"""updated/created plus default value migration.

Revision ID: 5dc65bfb2b06
Revises: f465f86063fa
Create Date: 2023-12-09 17:21:22.475942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5dc65bfb2b06"
down_revision = "f465f86063fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Grades", schema=None) as batch_op:
        batch_op.add_column(sa.Column("createdAt", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("updatedAt", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Grades", schema=None) as batch_op:
        batch_op.drop_column("updatedAt")
        batch_op.drop_column("createdAt")

    # ### end Alembic commands ###
