"""variable renamed migration.

Revision ID: 5fa54245abf7
Revises: 5dc65bfb2b06
Create Date: 2023-12-09 21:57:48.125622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5fa54245abf7"
down_revision = "5dc65bfb2b06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Grades", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_grade", sa.Double(), nullable=True))
        batch_op.add_column(sa.Column("second_grade", sa.Double(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column("firstGrade")
        batch_op.drop_column("secondGrade")
        batch_op.drop_column("updatedAt")
        batch_op.drop_column("createdAt")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Grades", schema=None) as batch_op:
        batch_op.add_column(sa.Column("createdAt", sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column("updatedAt", sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column("secondGrade", sa.DOUBLE(), nullable=True))
        batch_op.add_column(sa.Column("firstGrade", sa.DOUBLE(), nullable=True))
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("second_grade")
        batch_op.drop_column("first_grade")

    # ### end Alembic commands ###
